export const dsKhoa = [
    "Tim mạch",
    "Da liễu",
    "Nội tiết",
    "Tiêu hóa",
    "Huyết học",
    "Thận",
    "Thần kinh",
    "Ung bướu",
    "Mắt",
    "Chấn thương chỉnh hình",
    "Tai mũi họng",
    "Sản phụ khoa",
    "Nhi",
    "Tâm thần",
    "Phổi",
    "Lão khoa",
    "Răng hàm mặt",
    "Phục hồi chức năng",
    "Nội Tổng Quát",
    "Nội Hô Hấp"
];